# Generated by Django 5.2.7 on 2025-11-16 20:51

from django.db import migrations
from decimal import Decimal
from datetime import time


def add_sample_data(apps, schema_editor):
    VehicleType = apps.get_model('pricing', 'VehicleType')
    PeakHour = apps.get_model('pricing', 'PeakHour')
    PromoCode = apps.get_model('pricing', 'PromoCode')
    from django.utils import timezone

    # Create Vehicle Types
    care_connect_go = VehicleType.objects.create(
        name='standard',
        display_name='Care Connect Go',
        description='Affordable rides for everyday travel',
        icon='car',
        capacity=4,
        base_fare=Decimal('15.00'),
        per_km_rate=Decimal('12.00'),
        per_minute_rate=Decimal('1.50'),
        minimum_fare=Decimal('30.00'),
        is_elderly_assisted=False,
        is_active=True,
        priority=1
    )

    care_connect_comfort = VehicleType.objects.create(
        name='premium',
        display_name='Care Connect Comfort',
        description='Premium vehicles with extra comfort and space',
        icon='car_premium',
        capacity=4,
        base_fare=Decimal('25.00'),
        per_km_rate=Decimal('18.00'),
        per_minute_rate=Decimal('2.00'),
        minimum_fare=Decimal('50.00'),
        is_elderly_assisted=False,
        is_active=True,
        priority=2
    )

    care_connect_assist = VehicleType.objects.create(
        name='elderly_assisted',
        display_name='Care Connect Assist',
        description='Specialized service with trained drivers for elderly passengers',
        icon='accessible',
        capacity=3,
        base_fare=Decimal('30.00'),
        per_km_rate=Decimal('20.00'),
        per_minute_rate=Decimal('2.50'),
        minimum_fare=Decimal('60.00'),
        is_elderly_assisted=True,
        is_active=True,
        priority=3
    )

    care_connect_luxury = VehicleType.objects.create(
        name='luxury',
        display_name='Care Connect Luxury',
        description='High-end vehicles for a premium experience',
        icon='car_luxury',
        capacity=4,
        base_fare=Decimal('50.00'),
        per_km_rate=Decimal('30.00'),
        per_minute_rate=Decimal('3.00'),
        minimum_fare=Decimal('100.00'),
        is_elderly_assisted=False,
        is_active=True,
        priority=4
    )

    # Create Peak Hours
    # Morning Rush (5am - 8am) - Weekdays
    for day in range(0, 5):  # Monday to Friday
        PeakHour.objects.create(
            name='Morning Rush',
            day_of_week=day,
            start_time=time(5, 0),
            end_time=time(8, 0),
            multiplier=Decimal('1.5'),
            is_active=True
        )

    # Evening Rush (4pm - 6pm) - Weekdays
    for day in range(0, 5):  # Monday to Friday
        PeakHour.objects.create(
            name='Evening Rush',
            day_of_week=day,
            start_time=time(16, 0),
            end_time=time(18, 0),
            multiplier=Decimal('1.5'),
            is_active=True
        )

    # Weekend Evening (6pm - 10pm) - Friday & Saturday
    for day in [4, 5]:  # Friday, Saturday
        PeakHour.objects.create(
            name='Weekend Evening',
            day_of_week=day,
            start_time=time(18, 0),
            end_time=time(22, 0),
            multiplier=Decimal('1.3'),
            is_active=True
        )

    # Create Sample Promo Codes
    PromoCode.objects.create(
        code='WELCOME20',
        description='20% off your first ride (max R50)',
        discount_type='percentage',
        discount_value=Decimal('20.00'),
        max_discount=Decimal('50.00'),
        min_fare=Decimal('30.00'),
        max_uses=None,
        uses_count=0,
        valid_from=timezone.now(),
        valid_until=timezone.now().replace(year=timezone.now().year + 1),
        is_active=True
    )

    PromoCode.objects.create(
        code='ELDERLY50',
        description='R50 off Care Connect Assist rides',
        discount_type='fixed',
        discount_value=Decimal('50.00'),
        max_discount=None,
        min_fare=Decimal('60.00'),
        max_uses=None,
        uses_count=0,
        valid_from=timezone.now(),
        valid_until=timezone.now().replace(year=timezone.now().year + 1),
        is_active=True
    )

    PromoCode.objects.create(
        code='RIDE100',
        description='R100 off rides over R200',
        discount_type='fixed',
        discount_value=Decimal('100.00'),
        max_discount=None,
        min_fare=Decimal('200.00'),
        max_uses=100,
        uses_count=0,
        valid_from=timezone.now(),
        valid_until=timezone.now().replace(month=12, day=31),
        is_active=True
    )


def remove_sample_data(apps, schema_editor):
    VehicleType = apps.get_model('pricing', 'VehicleType')
    PeakHour = apps.get_model('pricing', 'PeakHour')
    PromoCode = apps.get_model('pricing', 'PromoCode')

    VehicleType.objects.all().delete()
    PeakHour.objects.all().delete()
    PromoCode.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_sample_data, remove_sample_data),
    ]
