# Generated by Django 5.2.8 on 2025-12-22 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_phone", models.CharField(max_length=15)),
                (
                    "pickup_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("pickup_address", models.TextField()),
                (
                    "dropoff_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "dropoff_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("dropoff_address", models.TextField()),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("fare_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("booking_time", models.DateTimeField(auto_now_add=True)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                ("dropoff_time", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("special_requirements", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("passenger_rating", models.IntegerField(blank=True, null=True)),
                ("driver_rating", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="drivers.driver",
                    ),
                ),
                (
                    "elderly_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="api.elderlymember",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "-booking_time"],
                        name="bookings_bo_status_e83c41_idx",
                    ),
                    models.Index(
                        fields=["passenger", "-booking_time"],
                        name="bookings_bo_passeng_859b91_idx",
                    ),
                    models.Index(
                        fields=["driver", "-booking_time"],
                        name="bookings_bo_driver__d4e304_idx",
                    ),
                ],
            },
        ),
    ]
